### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [GuillermoAbadLopez/Quantum-Teleportation#1]
I recently came across your project Quantum-Teleportation and I noticed that the repository github.com/GuillermoAbadLopez/Quantum-Teleportation currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by GuillermoAbadLopez** [comment]
Hello Juan,

Thank you for the interest in the repo, and yes that's a great idea, I will definently consider it!

I don't know much about licensing, and I'm currently traveling on vacations, so I'll check the subject and see which one fits better next week, when I'm back, and update you on the subject.

Thanks again 🙌

**Comment by GuillermoAbadLopez** [comment]
Hello again @cbjuan,

After some investigation, I think the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) fits the repo really well 👌 

I just added it, thank you for the suggestion!

**Comment by cbjuan** [comment]
Thanks!

**Comment by GuillermoAbadLopez** [comment]
@cbjuan I guess you also asked, due to the repo using `qiskit`, which has Apache 2.0 itself, no?

So more than a decision, it was kind of mandatory... The ilusion of choise 😅

Well thanks anyway for pointing it out!
(I'll add it to all my projects that use `qiskit` 👍)
